apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        track: black
    spec:
      containers:
      - name: gateway
        image: my-co/gateway:v1
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 1536Mi
            cpu: 55m
        env:
          - name: MY_SECRET
            valueFrom:
              secretKeyRef:
                name: my
                key: secret
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 3
          failureThreshold: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 1
          failureThreshold: 3
          periodSeconds: 1
